### ISSUE TITLE
Linux error "undefined symbol: gdk_x11_window_get_xid"

### ISSUE THREAD

**Issue by ngjaying** [equoplatform/chromium-swt#68]
I tried this plugin on redhat enterprise. I cannot launch it because of the below error. Are there any dependencies that I have missed? Thanks. 

java.lang.UnsatisfiedLinkError: /home/devadmin/.swt/lib/linux/x86_64/chromium-3071/libchromium_swt-0901.so: undefined symbol: gdk_x11_window_get_xid
	at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries(NativeLibrary.java:87)
	at jnr.ffi.provider.jffi.NativeLibrary.getNativeLibraries(NativeLibrary.java:70)
	at jnr.ffi.provider.jffi.NativeLibrary.getSymbolAddress(NativeLibrary.java:49)
	at jnr.ffi.provider.jffi.NativeLibrary.findSymbolAddress(NativeLibrary.java:59)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:158)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:89)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:44)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:325)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:304)
	at org.eclipse.swt.chromium.Chromium.loadLib(Chromium.java:1108)
	at org.eclipse.swt.chromium.Chromium.<clinit>(Chromium.java:85)
	at org.eclipse.swt.chromium.Browser.<init>(Browser.java:32)

**Comment by gzunino** [comment]
Are you running on something different than GTK3 and X11 ?

**Comment by Baytars** [comment]
Came across the same issue in Deepin Linux. What's worse, if you drag the window containing the browser, the whole screen goes black. Judging from the cursor changing from normal one to Xming style, the browser might have caused the X display server to crash. Catastrophe!
At present I've changed my OS to Manjaro Linux and everything works fine for me after installing CEF Binaries via http://dl.maketechnology.io/chromium-cef/rls/repository. I will never use Deepin again because there are more issues than this in that OS.
Hope this will be helpful for you.
